### ISSUE TITLE
Meta-issue: unsupported prop types

### ISSUE THREAD

**Issue by sentience** [cultureamp/stencil-elm-output-target#8]
@sebpearce will provide pasted warnings once he gets his build working again.

Issues:
- [x] #3 Add support for number prop type
- [x] #4 Gracefully degrade for unsupported field types in object prop types
- [x] #5 Add support for Array-type props
- [x] #6 Add support for union type props
- [x] #7 Investigate need to explicitly ignore `undefined | ` for some prop types (was needed for optional enumerated string type?)

**Comment by sebpearce** [comment]
```

[ WARN  ]  Component "stencil-button" prop "onClick" of type () => void is not supported by Elm output target.


[ WARN  ]  Component "stencil-button" prop "onClick" of type () => void is not supported by Elm output target.


[ WARN  ]  Component "stencil-menu-dropdown" prop "position" of type { top: number bottom: number left: number right:
           number } | null is not supported by Elm output target.


[ WARN  ]  Component "stencil-menu-dropdown" prop "position" of type { top: number bottom: number left: number right:
           number } | null is not supported by Elm output target.


[ WARN  ]  Component "stencil-menu-item" prop "action" of type string | ((e: MouseEvent) => void) is not supported by
           Elm output target.


[ WARN  ]  Component "stencil-menu-item" prop "action" of type string | ((e: MouseEvent) => void) is not supported by
           Elm output target.


[ WARN  ]  Component "stencil-tag" prop "onDismiss" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "onMouseDown" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "onMouseLeave" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "truncateWidth" of type number is not supported by Elm output target.


[ WARN  ]  Component "stencil-tag" prop "onDismiss" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "onMouseDown" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "onMouseLeave" of type (e: MouseEvent) => void is not supported by Elm output
           target.


[ WARN  ]  Component "stencil-tag" prop "truncateWidth" of type number is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "avatar" of type JSX.Element is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "handleHamburgerClick" of type (event: MouseEvent) => void is not
           supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "primaryAction" of type PrimaryActionProps is not supported by Elm
           output target.


[ WARN  ]  Component "stencil-title-block" prop "defaultAction" of type StencilTitleBlockButtonProps is not supported
           by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "secondaryActions" of type SecondaryActionsProps is not supported by
           Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "secondaryOverflowMenuItems" of type StencilTitleBlockMenuItemProps[]
           is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "avatar" of type JSX.Element is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "handleHamburgerClick" of type (event: MouseEvent) => void is not
           supported by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "primaryAction" of type PrimaryActionProps is not supported by Elm
           output target.


[ WARN  ]  Component "stencil-title-block" prop "defaultAction" of type StencilTitleBlockButtonProps is not supported
           by Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "secondaryActions" of type SecondaryActionsProps is not supported by
           Elm output target.


[ WARN  ]  Component "stencil-title-block" prop "secondaryOverflowMenuItems" of type StencilTitleBlockMenuItemProps[]
           is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "primaryAction" of type PrimaryActionProps is not
           supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "defaultAction" of type StencilTitleBlockButtonProps is
           not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "overflowMenuItems" of type
           StencilTitleBlockMenuItemProps[] is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "primaryAction" of type PrimaryActionProps is not
           supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "defaultAction" of type StencilTitleBlockButtonProps is
           not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-main-actions" prop "overflowMenuItems" of type
           StencilTitleBlockMenuItemProps[] is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-secondary-actions" prop "secondaryActions" of type SecondaryActionsProps is
           not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-secondary-actions" prop "secondaryOverflowMenuItems" of type
           StencilTitleBlockMenuItemProps[] is not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-secondary-actions" prop "secondaryActions" of type SecondaryActionsProps is
           not supported by Elm output target.


[ WARN  ]  Component "stencil-title-block-secondary-actions" prop "secondaryOverflowMenuItems" of type
           StencilTitleBlockMenuItemProps[] is not supported by Elm output target.
```

**Comment by sentience** [comment]
All done, we think!
